channels:
  - conda-forge

dependencies:
  - python=3.10               # https://pyreadiness.org/3.10
  - pip=22.1.2                    # https://pip.pypa.io/en/stable/news
  - pip:
    - rpaframework==23.5.2        # https://rpaframework.org/releasenotes.html
    - robocorp==0.4.0             # https://pypi.org/project/robocorp
    - robocorp-browser==1.0.2     # https://pypi.org/project/robocorp-browser
    - robocorp-excel==0.4.0       # https://pypi.org/project/robocorp-excel
    - robocorp-http==0.2.0        # https://pypi.org/project/robocorp-http
    - loguru==0.5.3               # https://pypi.org/project/loguru
    - python-dotenv==0.19.1       # https://pypi.org/project/python-dotenv
